nodeLinker: node-modules

plugins:
  - checksum: ed8dadb66df330241a321bd0bac88ce7177abb39b56a0992a1475c0b8ceef01672e04049b1cda856645b1ebf7e30d5d77973a196cab3ec1105395a3f33f88780
    path: .yarn/plugins/@yarnpkg/plugin-catalogs.cjs
    spec: "https://raw.githubusercontent.com/toss/yarn-plugin-catalogs/main/bundles/%40yarnpkg/plugin-catalogs.js"
